name: aqar_com
description: A new version of real state application aqar com

publish_to: 'none'

version: 1.0.4+26

environment:
  sdk: '>=3.0.0 <3.10.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  easy_localization: ^3.0.3
  dio: ^4.0.6
  flutter_bloc: ^8.1.3
  pin_code_text_field: ^1.8.0
  geolocator: ^9.0.2
  google_maps_flutter: ^2.5.0
  flutter_screenutil: ^5.9.0
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  image_picker: ^1.0.4
  video_thumbnail: ^0.5.3
  path_provider: ^2.1.1
  google_maps_place_picker_mb: ^2.0.0-mb.13
  syncfusion_flutter_sliders: ^23.1.42
  popover: ^0.2.8+2
  expandable: ^5.0.1
  custom_map_markers: ^0.0.2+1
  url_launcher: ^6.1.14
  # firebase & notifications
  firebase_core: ^2.19.0
  firebase_messaging: ^14.7.1
  flutter_local_notifications: ^16.1.0
  in_app_review: ^2.0.8
  lottie: ^2.7.0
  video_player: ^2.7.2
  chewie: ^1.7.1
  html: ^0.15.4
  firebase_dynamic_links: ^5.4.1
  webview_flutter: ^4.4.1
  webview_flutter_android: ^3.12.0
  permission_handler: ^11.0.1
  share_plus: ^7.2.1
  cached_network_image: ^3.3.0
  photo_view: ^0.14.0
  should_rebuild: ^1.0.1
  rxdart: ^0.27.7
  font_awesome_flutter: ^10.6.0
  flutter_staggered_animations: ^1.1.1
  readmore: ^2.2.0
  flutter_html: ^3.0.0-alpha.6
  share: ^2.0.4
  external_app_launcher: ^3.1.0
  workmanager: ^0.5.2
  dio_logger: ^4.0.8+8







dev_dependencie:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.4
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  image: assets/images/icon.png
  background_image: assets/images/splash-background.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center

#  flutter_lints: ^2.0.0

flutter_icons:
  # Command Line to change the icon
  # flutter pub run flutter_launcher_icons:main
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo-without-boarder.png"
  adaptive_icon_background: "#ffffff"
  remove_alpha_ios: true


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/new/
    - assets/new/azza/
    - assets/new/New folder/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/NeoSansArabicRegular.ttf
          weight: 400
        - asset: assets/fonts/NeoSansArabicMedium.ttf
          weight: 500
        - asset: assets/fonts/NeoSansArabicBold.ttf
          weight: 700
